# This file's purpose is to automatically deploy website updates using FTP.
# https://savjee.be/2019/04/gitlab-ci-deploy-to-ftp-with-lftp/

stages:
    - deploy

deploy:
    stage: deploy
    # Only if push is on master branch with a change to any of website's files and subirectories.
    only:
        refs:
            - master
        changes:
            - website/**/*
    script:
        - apt-get update -qq && install -y -qq lftp
        - lftp -e "open sftp://sdweb.ece.iastate.edu; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete website/ var/www/users/sddec21-11/www/; bye"