[[printerAction]]
device = 'Laser'
port = 25565
actions = [
	'F, C, S4 M5400, I4 M0, R',
	'F, C, S1 M5400, I1 M-0, R',
	'F, C, S2 M5400, S3 M 5400, I2 M0, I3 M-0, R',
	'F, C, I2 M-1800, I3 M13000, R',
	'F, C, S1M 3000, S2M 3000, I1M -1800, I2M -0, R',
]
gcode = 'M201'
