[Info]
datetime = '29-Nov-2021 11:31:23'
gcodepath = './test_files/home.gcode'
outputpath = './test_files/home.toml'

[[printerAction]]
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, S4 M5400, I4 M0, R,\r',
	'F, C, S1 M5400, I1 M-0, R,\r',
	'F, C, S2 M5400, S3 M5400, I2 M0, I3 M-0, R,\r',
	'F, C, I2 M-1800, I3 M13000, R,\r',
]
gcode = 'M200'

[[printerAction]]
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, S1 M3000, S2 M3000, I1 M-1800, I2 M--20000, R,\r',
]
gcode = 'M200'

